SpeechTherapyCenter/Controllers/ManagerController.cs
using Microsoft.AspNetCore.Mvc;
using Services;
using Services.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SpeechTherapyCenter.Controllers
{
    public class ManagerController : Controller
    {

        public ManagerService serviceManager { get; set; }

        public ManagerController(ManagerService service)
        {
            serviceManager = service;
        }


        // Shows all assigned employees
        public async Task<IActionResult> Index()
        {
            return View(await serviceManager.GetAll());
        }

        public async Task<IActionResult> GetWorker()
        {
            List<WorkerViewModel> result = await serviceManager.GetAll();
            return View("Index");
        }

        [HttpGet]
        public IActionResult AddWorker()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddWorker([Bind("FirstName, LastName, Email,Password,UserName,Country, Year, Salary,Internship,Position")] WorkerViewModel worker)
        {
            if (ModelState.IsValid)
            {
                await serviceManager.AddWorker(worker);
                return RedirectToAction(nameof(Index));
            }
            return Redirect("~/Home/Index");
        }

        // Deleting an worker
        public async Task<IActionResult> DeleteWorker(string? id)
        {
            await serviceManager.DeleteWorker(id);
            return Redirect("~/Home/Index");
        }

        // Add new role
        [HttpGet]
        public IActionResult AddRole()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddRole(CreateRoleViewModel roleModel)
        {
            if (ModelState.IsValid)
            {
                await serviceManager.AddRole(roleModel);
                return RedirectToAction(nameof(Index));
            }
            return Redirect("~/Home/Index");
        }

        // Add a new service
        [HttpGet]
        public IActionResult AddService()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddService([Bind("Title, Body,Date")] ServiceViewModel service)
        {
            if (ModelState.IsValid)
            {
                await serviceManager.AddService(service);
                return RedirectToAction(nameof(Index));
            }
            return Redirect("~/Home/Index");
        }
    }
}

SpeechTherapyCenter/Controllers/OfficeController.cs
using Microsoft.AspNetCore.Mvc;
using Services;
using Services.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SpeechTherapyCenter.Controllers
{
    public class OfficeController : Controller
    {
        public OfficeService serviceOffice { get; set; }

        public OfficeController(OfficeService service)
        {
            serviceOffice = service;
        }

        // Shows all posts
        public async Task<IActionResult> Index()
        {
            return View(await serviceOffice.GetAll());
        }

        public async Task<IActionResult> GetService()
        {
            List<ServiceViewModel> result = await serviceOffice.GetAll();
            return View("Index");
        }

        //Get service by ID
        public async Task<IActionResult> GetServiceById(string id)
        {
            ServiceViewModel result = await serviceOffice.GetServiceById(id);
            return View("_WorkerPartial", result);
        }
    }
}

SpeechTherapyCenter/Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;
using Services;
using Services.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SpeechTherapyCenter.Controllers
{
    public class PostController : Controller
    {
        public PostService servicePost { get; set; }

        public PostController(PostService service)
        {
            servicePost = service;
        }

        // Shows all posts
        public async Task<IActionResult> Index()
        {
            return View(await servicePost.GetAll());
        }

        public async Task<IActionResult> GetPost()
        {
            List<PostViewModel> result = await servicePost.GetAll();
            return View("Index");
        }

        [HttpGet]
        public IActionResult AddPost()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddPost([Bind("Title, Body")] PostViewModel post)
        {
            if (ModelState.IsValid)
            {
                await servicePost.AddPost(post);
                return RedirectToAction(nameof(Index));
            }
            return Redirect("~/Home/Index");
        }

        // Deleting post
        public async Task<IActionResult> DeletePost(string? id)
        {
            await servicePost.DeletePost(id);
            return Redirect("~/Home/Index");
        }
    }
}

SpeechTherapyCenter/Controllers/WorkerController.cs
using Microsoft.AspNetCore.Mvc;
using Services;
using Services.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SpeechTherapyCenter.Controllers
{
    public class WorkerController : Controller
    {
        public WorkerService serviceWork { get; set; }

        public WorkerController(WorkerService service)
        {
            serviceWork = service;
        }

        // Shows all workers
        public async Task<IActionResult> Index()
        {
            return View(await serviceWork.GetAll());
        }

        public async Task<IActionResult> GetPost()
        {
            List<WorkerViewModel> result = await serviceWork.GetAll();
            return View("Index");
        }

        //Get worker by ID
        public async Task<IActionResult> GetWorkerById(string id)
        {
            WorkerViewModel result = await serviceWork.GetWorkerById(id);
            return View("_WorkerPartial", result);
        }
    }
}

SpeechTherapyCenter/Views/Shared/_Layout.cshtml
<style>
    .logo h1 span {
        font-size: 25px;
        margin: 0;
        padding: 4px 0;
        line-height: 1;
        font-weight: 300;
        letter-spacing: 3px;
        text-transform: uppercase;
        color: #683aa4;
        font: italic small-caps bold 16px/2 cursive;
    }

    .first {
        margin-left: 3%;
    }

</style>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <link rel="shortcut icon" type="image/png" href="~/Images/Favicon.png" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Логопедичен център "Слънце"</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                    <img src="~/Images/Favicon.png" height="30" />
                    <div class="logo">
                        <h1 class="text-light"><span>Слънце</span></h1>
                    </div>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="first"></li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Начало</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">За нас</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Office" asp-action="Index">Услуги</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Worker" asp-action="Index">Служители</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="Index">Постове</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Manager" asp-action="Index">Workers</a>
                        </li>
                    </ul>
                </div>
            </div>
            <partial name="_LoginPartial" />
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SpeechTherapyCenter/Views/Shared/_ServicePartial.cshtml
@model ServiceViewModel

<style>
    .services .icon-box {
        text-align: center;
        border: 1px solid #ededed;
        padding: 80px 20px;
        transition: all ease-in-out 0.3s;
    }

        .services .icon-box .icon {
            margin: 0 auto;
            width: 64px;
            height: 64px;
            background: #e96b56;
            border-radius: 5px;
            transition: all .3s ease-out 0s;
            display: flex;
            align-items: center;
            justify-content: center;
            margin-bottom: 20px;
            transform-style: preserve-3d;
        }

            .services .icon-box .icon i {
                color: #fff;
                font-size: 28px;
            }

            .services .icon-box .icon::before {
                position: absolute;
                content: '';
                left: -8px;
                top: -8px;
                height: 100%;
                width: 100%;
                background: #fbe2dd;
                border-radius: 5px;
                transition: all .3s ease-out 0s;
                transform: translateZ(-1px);
            }

        .services .icon-box h4 {
            font-weight: 700;
            margin-bottom: 15px;
            font-size: 24px;
        }

            .services .icon-box h4 a {
                color: #545454;
            }

        .services .icon-box p {
            line-height: 24px;
            font-size: 14px;
            margin-bottom: 0;
        }

        .services .icon-box:hover {
            background: #e96b56;
            border-color: #e96b56;
        }

            .services .icon-box:hover .icon {
                background: #fff;
            }

                .services .icon-box:hover .icon i {
                    color: #e96b56;
                }

                .services .icon-box:hover .icon::before {
                    background: #ef9383;
                }

            .services .icon-box:hover h4 a, .services .icon-box:hover p {
                color: #fff;
            }
</style>

<body>
        <section id="services" class="services">
            <div class="container">

                <div class="section-title" data-aos="fade-up">
                    <h2>Нашите услуги</h2>
                </div>

                <div class="row">
                    <div class="col-lg-4 col-md-6 d-flex align-items-stretch">
                        <div class="icon-box">
                            <div class="icon"><i class="bx bxl-dribbble"></i></div>
                            <h4><a href="">@Model.Title</a></h4>
                            <p>@Model.Body</p>
                        </div>
                    </div>
                    


                    <div class="col-lg-4 col-md-6 d-flex align-items-stretch mt-4">
                        <div class="icon-box">
                            <div class="icon"><i class="bx bx-arch"></i></div>
                            <h4><a href="">@Model.Title</a></h4>
                            <p>@Model.Body</p>
                        </div>
                    </div>

                </div>

            </div>
        </section>
    }
</body>